logging:
  file:
    name: logs/app.log
    max-size: 10 MB
  pattern:
    console: "%d %-5level [%thread] %logger{0} : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: WARN
    com.example: debug
app:
  hello: Hello World from config
